config/routes.rb
Index::Application.routes.draw do
  root :to => "pages/home_index#index"
	scope :pages do
	  resources :home_index
	end
	match "admin" => "admin/dashboard#index"
	namespace :admin do
		root :to => "admin/dashboard#index"
		resources :dashboard
		resources :posts do
			put :updatePost, :on => :collection
		 resources :attachments
		end
	end
	resources :posts, :comments
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :path, :description, :post_id
  belongs_to :post
  mount_uploader :path, PostUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/pages/home_index.rb
class Pages::HomeIndex < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :author
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments
  # mount_uploader :path, PostUploader
end

app/controllers/admin/attachments_controller.rb
class Admin::AttachmentsController < ApplicationController
  def index
  end

  def new
  	@post = Post.find(params[:post_id])
  	@attachment = @post.attachments.new
  	@attachs = @post.attachments.find_all_by_post_id(params[:post_id]).reverse
  	@attach = @post.attachments.order("created_at").last
    @all = @post.attachments.find(:all)
  end

  def create
  	@post = Post.find(params[:post_id])
    @all = @post.attachments.find(:all)
  	# @attachment = @post.attachments.new(params[:admin_attachment])
		params[:attachment][:path].each do |image|
			@params = {}
			@params['path'] = image
			@attachment = @post.attachments.create(@params)
		end
		if @attachment.save
      @attachs = @post.attachments.find_all_by_post_id(params[:post_id]).reverse
      @attach = @post.attachments.order("created_at").last
      respond_to do |format|
        format.js {render "create", :locals => {:attach => @attachs}}
      end
		end
  end

  def show
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@attachment = @post.attachments.find_by_post_id(params[:post_id])
  	# FileUtils.remove_dir("#{Rails.root}/public/uploads/attachment/path/#{@post.id}/#{@attachment.id}", :force => true)
  	@attachment.destroy
  	redirect_to :back
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	layout 'admin'
	def index

	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	layout 'admin'
	def index
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
		@attach = @post.attachments.find_all_by_post_id(params[:id])
	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(params[:post])
		if @post.save
	  	respond_to do |format|
		    format.html { redirect_to new_admin_post_attachment_path(@post) }
		    format.js   { }
	  	end
		else
			flash[:notice] = "Did not create post because of errors"
			redirect_to admin_posts_path
		end
	end
	def edit
		@post = Post.find(params[:id])
		@attach = @post.attachments.find_all_by_post_id(params[:id])
	end
	def update
		@post = Post.find(params[:id])
		@post.update_attributes(params[:post])
		redirect_to [:admin, @post]
	end
	def destroy
		@post = Post.find(params[:id])
		FileUtils.remove_dir("#{Rails.root}/public/uploads/attachment/path/#{@post.id}", :force => true)
		@post.destroy
		redirect_to admin_posts_path
	end
	def updatePost
		@post = Post.find(84)
		@post.update_attributes(params[:post])
		redirect_to [:admin, @post]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages/home_index_controller.rb
class Pages::HomeIndexController < ApplicationController
	def index

	end
end

app/helpers/admin/attachments_helper.rb
module Admin::AttachmentsHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		this = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
		this.render(text).html_safe
	end
end

app/helpers/home_index_helper.rb
module HomeIndexHelper
end

app/views/admin/attachments/_ajax-attach.html.erb
<%= image_tag attach.path, :width => '200px', :class => 'uploaded' %>
<%= button_to "Destroy", admin_post_attachment_path(current, pic), :method => "delete" %>

app/views/admin/attachments/_attachments.html.erb
<div class="attachments">
<% @attachs.each do |pic| %>
	<%= image_tag pic.path, :width => 50, :class => "uploaded" %>
	<input type="button" onClick="addPost()" class="addPost">
<% end %>
</div>

app/views/admin/attachments/create.js.erb
		var img = $("<%= escape_javascript("#{render :partial => 'attachments', :locals => {:attach => attach}}").html_safe %>");
		$('.attachments').replaceWith(img);

app/views/admin/attachments/index.html.erb
<h1>Admin::Attachments#index</h1>
<p>Find me in app/views/admin/attachments/index.html.erb</p>

app/views/admin/attachments/new.html.erb
<%= content_for :head do %>
	<%= javascript_include_tag "application", "attachments/add-attachments" %>
	<%= stylesheet_link_tag "attach_new" %>
<% end %>
<%= form_for @post, :url => {:controller => "posts", :action => "updatePost"} , :method => "put" do |t|%>
	<%= t.hidden_field :id, :value => @post.id %>
	<%= t.text_area :content, :class => "post-content" %> <br>
	<%= t.submit "Publish Post" %>
<% end %>
<hr>
<h1>Add Images</h1>
<%= form_for [:admin, @post, @attachment], :remote => true, :class => "image-form" do |f| %>
	<%= f.hidden_field :post_id, :value => @post.id %>
	<%= f.file_field :path, :multiple => true %> <br>
	<%= f.submit "Upload" %>
<% end %>
<hr>
<%= render 'admin/attachments/attachments' %>

app/views/admin/attachments/show.html.erb
<h1>Admin::Attachments#show</h1>
<p>Find me in app/views/admin/attachments/show.html.erb</p>

app/views/admin/posts/edit.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "admin/post_edit" %>
	<%= javascript_include_tag "admin/posts/post_edit" %>
<% end %>
<%= form_for [:admin, @post] do |t| %>
	<%= t.label :title %> <br>
	<%= t.text_field :title %>
	<br>
	<%= t.label :author %> <br>
	<%= t.text_field :author %>
	<br>
	<%= t.label :content %> <br>
	<%= t.text_area :content %>
	<br>
	<%= t.submit "Update Post" %>
<% end %>
<%= label_tag :attachments %> <br>
<br>
<% for pic in @attach do %>
	<div class="image">
		<%= image_tag pic.path, :height => "100px"%>
		<%= button_to "X", admin_post_attachment_path(@post, pic), :method => :delete %>
		<br>
	</div>
<% end %>
<%= link_to "Add Attachments", new_admin_post_attachment_path(@post) %>

app/views/admin/posts/index.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "admin/posts_index" %>
<% end %>
<% @posts.each do |post| %>
<%= link_to admin_post_path(post) do %>
	<div class="post">
		<p class="title">
			<%= post.title %>
		</p>  <br>

		<%= markdown(truncate(post.content, :length => 200)) %>
	</div>
	<% end %>
<% end %>
<%= link_to "Create New Post", new_admin_post_path %> <br>

app/views/admin/posts/new.html.erb
<%= form_for [:admin, @post], :html => {:multipart => true} do |t| %>
	<%= t.label :title %> <br>
	<%= t.text_field :title %>
	<br>
	<%= t.label :author %> <br>
	<%= t.text_field :author %>
	<br>
	<%= t.label :content %> <br>
	<%= t.text_area :content %>
<br>
	<%= t.submit "Create Post" %>
<% end %>

app/views/admin/posts/show.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "admin/post_show" %>
	<%= javascript_include_tag "admin/posts/post_show" %>
<% end %>
<div class="content">
	<h2 class="title"><%= @post.title %></h2><br>
	<%= markdown(@post.content) %> <br>
</div>
<div class="author"><p><%= @post.author %></p></div>
<%= link_to "Edit", edit_admin_post_path(@post) %>
<%= button_to "Delete", admin_post_path(@post), :method => :delete %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesignSlideLab Web Designer's resources and tutorials</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", "admin/admin" %>
  <%= javascript_include_tag "jquery" %>
 	<%= yield :head %>
 	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container clearfix">
	<header class="header clearfix">
		<div class="company">
			<%= link_to admin_posts_url do %>
				<%= image_tag "designslide_logo.png", :alt => "DesignSlideLab Logo", :class => "logo" %>
				<h1> Admin<span style="color: #40E692;">::</span>DesignSlideLab </h1>
			<% end %>
		</div>
		<nav>
			<ul>
				<li>
					<%= link_to "Statistics" %>
				</li>
				<li>
					<%= link_to "Posts" %>
				</li>
			</ul>
		</nav>
		</header>
		<section class="page-content clearfix">
			<%= yield %>
		</section>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesignSlideLab Web Designer's resources and tutorials</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", "layout" %>

  <%= javascript_include_tag "jquery", "home_index", "header" %>
	<%= yield :head %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container clearfix">
	<header class="header clearfix">
		<div class="company">
			<%= image_tag "designslide_logo.png", :alt => "DesignSlideLab Logo", :class => "logo" %>
			<h1> designslidelab </h1>
		</div>
		<nav>
			<ul>
				<li>
					<%= link_to "Shop" %>
				</li>
				<li>
					<%= link_to "Blog" %>
				</li>
				<li>
					<%= link_to "Works" %>
				</li>
				<li>
					<%= link_to "About" %>
				</li>
			</ul>
		</nav>
		</header>
		<section class="page-content clearfix">
			<%= yield %>
		</section>
</div>

</body>
</html>

app/views/pages/home_index/index.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "home_index" %>
<% end %>
<section class="articles">
	<ul>
		<li class="article-item">
			<div class="timeline_item">
				<p>15 <br/>May</p>
				<div class="line"></div>
			</div>
			<article class="content clearfix">
				<h1>The Art of Website Design</h1>
				<div class="article_img fit">
					<%= image_tag "placeholder1.png" %>
				</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, dolores, animi ipsa culpa dicta expedita hic maiores. Dolorum, cum, doloribus optio sapiente possimus fuga labore culpa excepturi vitae assumenda enim!</p>
			</article>
		</li>
		<li class="article-item">
			<div class="timeline_item">
				<p>19 <br/>Mar</p>
				<div class="line"></div>
			</div>
			<article class="content clearfix">
				<h1>Newest Logo Dribbble Had</h1>
				<div class="article_img">
					<%= image_tag "background-pic.jpg" %>
				</div>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, accusantium, reiciendis, dolorum enim ratione ipsum sit sunt cum officiis id quidem aliquam debitis dicta ullam quo deserunt similique? Commodi, iure. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id, officiis, quisquam fugit alias laboriosam tempore perferendis ratione et sint laborum aut porro eaque obcaecati repellat sunt nobis atque eum maxime.</p>
			</article>
		</li>
	</ul>
</section>
<section class="sidebar">
	<h3>Products</h3>
	<div class="product-item clearfix">
		<%= image_tag "UI-example.png" %>
		<div class="product-info">
			<h5>Code UI Kit</h5>
			<div class="price">$89</div>
			<p>All the code snippets you will ever need!</p>
		</div>
	</div>
</section>